trigger: none

variables:
- group: Repo_Env

pool:
  vmImage: 'ubuntu-latest'

steps:


- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(e8850995-7132-4e71-b8b6-83830937405c)'
    azureContainerRegistry: '{"loginServer":"daytrader.azurecr.io", "id" : "/subscriptions/e8850995-7132-4e71-b8b6-83830937405c/resourceGroups/Daytrader/providers/Microsoft.ContainerRegistry/registries/daytrader"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d'

# task: CmdLine@2
#  inputs:
#    script: |
#      wget https://openssl.org/source/openssl-1.0.2k.tar.gz
#      tar -xvf openssl-1.0.2k.tar.gz
#      cd openssl-1.0.2k/
#      sudo ./config --prefix=`pwd`/local --openssldir=/usr/lib/ssl enable-ssl2 enable-ssl3 no-shared
#      sudo make depend
#      sudo make
#      sudo make -i install
#      sudo cp local/bin/openssl /usr/local/bin/
#      curl -k https://localhost:5443
#      day-trader-java-app/daytrader-curl-testing/curl_commands.sh

#- task: Bash@3
# inputs:
#    filePath: 'day-trader-java-app/daytrader-curl-testing/curl_commands.sh'

- task: Bash@3
  continueOnError: true
  inputs:
    filePath: 'day-trader-java-app/daytrader-postman-testing/test_all.sh'
    workingDirectory: 'day-trader-java-app/daytrader-postman-testing/'
    failOnStderr: true


- task: PublishTestResults@2
  #continueOnError: true
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'day-trader-java-app/daytrader-postman-testing/postman_results/**.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(e8850995-7132-4e71-b8b6-83830937405c)'
    azureContainerRegistry: '{"loginServer":"daytrader.azurecr.io", "id" : "/subscriptions/e8850995-7132-4e71-b8b6-83830937405c/resourceGroups/Daytrader/providers/Microsoft.ContainerRegistry/registries/daytrader"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'logs daytrader-accounts'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(e8850995-7132-4e71-b8b6-83830937405c)'
    azureContainerRegistry: '{"loginServer":"daytrader.azurecr.io", "id" : "/subscriptions/e8850995-7132-4e71-b8b6-83830937405c/resourceGroups/Daytrader/providers/Microsoft.ContainerRegistry/registries/daytrader"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'logs daytrader-gateway'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(e8850995-7132-4e71-b8b6-83830937405c)'
    azureContainerRegistry: '{"loginServer":"daytrader.azurecr.io", "id" : "/subscriptions/e8850995-7132-4e71-b8b6-83830937405c/resourceGroups/Daytrader/providers/Microsoft.ContainerRegistry/registries/daytrader"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'logs daytrader-portfolios'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(e8850995-7132-4e71-b8b6-83830937405c)'
    azureContainerRegistry: '{"loginServer":"daytrader.azurecr.io", "id" : "/subscriptions/e8850995-7132-4e71-b8b6-83830937405c/resourceGroups/Daytrader/providers/Microsoft.ContainerRegistry/registries/daytrader"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'logs daytrader-quotes'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(e8850995-7132-4e71-b8b6-83830937405c)'
    azureContainerRegistry: '{"loginServer":"daytrader.azurecr.io", "id" : "/subscriptions/e8850995-7132-4e71-b8b6-83830937405c/resourceGroups/Daytrader/providers/Microsoft.ContainerRegistry/registries/daytrader"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'logs daytrader-web'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(e8850995-7132-4e71-b8b6-83830937405c)'
    azureContainerRegistry: '{"loginServer":"daytrader.azurecr.io", "id" : "/subscriptions/e8850995-7132-4e71-b8b6-83830937405c/resourceGroups/Daytrader/providers/Microsoft.ContainerRegistry/registries/daytrader"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'down'

- script: |
    echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
    az devops configure --defaults organization=https://dev.azure.com/AlphaGX project="GXEnablement" --use-git-aliases true
    if [[ $(Recipe) == R1 ]]
    then
      az pipelines run --branch master --name "40.3 Kubernetes Deploy - EKS" -p GXEnablement
    elif [[ $(Recipe) == R2 ]]
    then
      az pipelines run --branch master --name "40.1 Kubernetes Deploy - AKS" -p GXEnablement
    elif [[ $(Recipe) == R3 ]]
    then
      az pipelines run --branch master --name "40.1 Kubernetes Deploy - AKS" -p GXEnablement
    fi
  env:
    AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
  displayName: 'Triggering next pipeline'