apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daytrader-gateway
  name: daytrader-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daytrader-gateway
  template:
    metadata:
      labels:
        app: daytrader-gateway
    spec:
      containers:
      - name: daytrader-gateway
        image: tnshibu/daytrader-gateway:1.0
        imagePullPolicy: Always
        
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m                    
        
        
        ports:
        - containerPort: 2443
          protocol: TCP
        readinessProbe:  
          httpGet:
            path: /health
            scheme: HTTPS
            port: 2443
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        livenessProbe:  
          httpGet:
            path: /health
            scheme: HTTPS
            port: 2443
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 4
        env:
        - name: ACCOUNTS_SERVICE_ROUTE
          value: https://daytrader-accounts
        - name: GATEWAY_SERVICE_ROUTE
          value: https://daytrader-gateway
        - name: PORTFOLIOS_SERVICE_ROUTE
          value: https://daytrader-portfolios
        - name: QUOTES_SERVICE_ROUTE
          value: https://daytrader-quotes
        - name: GET_HOSTS_FROM
          value: dns
